config/routes.rb
Rails.application.routes.draw do
  get 'inicio/index'
  root 'inicio#index'
  devise_for :users
  resources :funcionarios
  resources :visitantes
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
      user ||= User.new  # Usuário convidado
  
      if user.admin?
        can :manage, :all  # Permissões de administrador
      else
        can :read, :all    # Permissões padrão para usuários não administradores
      end
    end
  end
    # Define abilities for the user here. For example:
    #
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/funcionario.rb
class Funcionario < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         def admin?
          email == 'fabriciofilho435@gmail.com'  # Este é o administrador
        end
      end

app/models/visitante.rb
class Visitante < ApplicationRecord

    mount_uploader :foto, ImageUploader

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/funcionarios_controller.rb
class FuncionariosController < ApplicationController
  before_action :set_funcionario, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  load_and_authorize_resource

  # GET /funcionarios or /funcionarios.json
  def index
    @funcionarios = Funcionario.all
  end

  # GET /funcionarios/1 or /funcionarios/1.json
  def show
  end

  # GET /funcionarios/new
  def new
    @funcionario = Funcionario.new
  end

  # GET /funcionarios/1/edit
  def edit
  end

  # POST /funcionarios or /funcionarios.json
  def create
    @funcionario = Funcionario.new(funcionario_params)

    respond_to do |format|
      if @funcionario.save
        format.html { redirect_to funcionario_url(@funcionario), notice: "Funcionario criado com sucesso." }
        format.json { render :show, status: :created, location: @funcionario }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @funcionario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /funcionarios/1 or /funcionarios/1.json
  def update
    respond_to do |format|
      if @funcionario.update(funcionario_params)
        format.html { redirect_to funcionario_url(@funcionario), notice: "Funcionario Atualizado com sucesso." }
        format.json { render :show, status: :ok, location: @funcionario }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @funcionario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /funcionarios/1 or /funcionarios/1.json
  def destroy
    @funcionario.destroy!

    respond_to do |format|
      format.html { redirect_to funcionarios_url, notice: "Funcionario deletado com sucesso." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_funcionario
      @funcionario = Funcionario.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def funcionario_params
      params.require(:funcionario).permit(:nome, :cpf, :rg, :telefone, :secretaria, :cargo, :unidade)
    end
end

app/controllers/inicio_controller.rb
class InicioController < ApplicationController
  def index
  end
end

app/controllers/visitantes_controller.rb
class VisitantesController < ApplicationController
  before_action :set_visitante, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  # GET /visitantes or /visitantes.json
  def index
    @visitantes = Visitante.all
  end

  # GET /visitantes/1 or /visitantes/1.json
  def show
  end

  # GET /visitantes/new
  def new
    @visitante = Visitante.new
  end

  # GET /visitantes/1/edit
  def edit
  end

  # POST /visitantes or /visitantes.json
  def create
    @visitante = Visitante.new(visitante_params)

    respond_to do |format|
      if @visitante.save
        format.html { redirect_to visitante_url(@visitante), notice: "Visitante was successfully created." }
        format.json { render :show, status: :created, location: @visitante }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @visitante.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /visitantes/1 or /visitantes/1.json
  def update
    respond_to do |format|
      if @visitante.update(visitante_params)
        format.html { redirect_to visitante_url(@visitante), notice: "Visitante was successfully updated." }
        format.json { render :show, status: :ok, location: @visitante }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @visitante.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /visitantes/1 or /visitantes/1.json
  def destroy
    @visitante.destroy!

    respond_to do |format|
      format.html { redirect_to visitantes_url, notice: "Visitante was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_visitante
      @visitante = Visitante.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def visitante_params
      params.require(:visitante).permit(:nome, :cpf, :rg, :telefone, :foto, :visitou_em)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/funcionarios_helper.rb
module FuncionariosHelper
end

app/helpers/inicio_helper.rb
module InicioHelper
end

app/helpers/visitantes_helper.rb
module VisitantesHelper
end

app/views/funcionarios/_form.html.erb
<%= form_with(model: funcionario) do |form| %>
  <% if funcionario.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(funcionario.errors.count, "error") %> prohibited this funcionario from being saved:</h2>

      <ul>
        <% funcionario.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nome, style: "display: block" %>
    <%= form.text_field :nome %>
  </div>

  <div>
    <%= form.label :cpf, style: "display: block" %>
    <%= form.text_field :cpf %>
  </div>

  <div>
    <%= form.label :rg, style: "display: block" %>
    <%= form.text_field :rg %>
  </div>

  <div>
    <%= form.label :telefone, style: "display: block" %>
    <%= form.text_field :telefone %>
  </div>

  <div>
    <%= form.label :secretaria, style: "display: block" %>
    <%= form.text_field :secretaria %>
  </div>

  <div>
    <%= form.label :cargo, style: "display: block" %>
    <%= form.text_field :cargo %>
  </div>

  <div>
    <%= form.label :unidade, style: "display: block" %>
    <%= form.text_field :unidade %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/funcionarios/_funcionario.html.erb
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

<div id="<%= dom_id funcionario %>">


<div class="container">
  <table class="table table-bordered">
    <tbody>
      <tr>
        <th>Nome:</th>
        <td><%= funcionario.nome %></td>
      </tr>
      <tr>
        <th>CPF:</th>
        <td><%= funcionario.cpf %></td>
      </tr>
      <tr>
        <th>Rg:</th>
        <td><%= funcionario.rg %></td>
      </tr>
      <tr>
        <th>Telefone:</th>
        <td><%= funcionario.telefone %></td>
      </tr>
      <tr>
        <th>Secretaria:</th>
        <td><%= funcionario.secretaria %></td>
      </tr>
      <tr>
        <th>Cargo:</th>
        <td><%= funcionario.cargo %></td>
      </tr>
      <tr>
        <th>Unidade:</th>
        <td><%= funcionario.unidade %></td>
      </tr>
    </tbody>
  </table>
</div>

app/views/funcionarios/edit.html.erb
<h1>Editando funcionario</h1>

<%= render "form", funcionario: @funcionario %>

<br>

<div>
  <%= link_to "Show this funcionario", @funcionario %> |
  <%= link_to "Back to funcionarios", funcionarios_path %>
</div>

app/views/funcionarios/index.html.erb
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
<!-- Mensagem de aviso -->
<p style="color: green"><%= notice %></p>

<!-- Seção de Funcionários -->
<div class="container mt-5">
  <% if user_signed_in? %>
    <div class="mb-4">
      <h1>Bem-vindo à seção de gerenciamento de funcionários</h1>
      <p>Lista de funcionários cadastrados</p>
    </div>

    <div class="mt-4">
    <% if current_user.admin? %>
      <%= link_to "Adicionar funcionário", new_funcionario_path, class: "btn btn-success" %>
      
      <% end %>
      
    </div>
  <% end %>

  <div id="funcionarios" class="mt-4">
    <table class="table">
      <thead>
        <tr>
          <th>Nome</th>
          <th>CPF</th>
          <th>RG</th>
          <th>Telefone</th>
          <th>Secretaria</th>
          <th>Unidade</th>
          <th>Ações</th>
        </tr>
      </thead>
      <tbody>
        <% @funcionarios.each do |funcionario| %>
          <tr>
            <td><%= funcionario.nome %></td>
            <td><%= funcionario.cpf %></td>
            <td><%= funcionario.rg %></td>
            <td><%= funcionario.telefone %></td>
            <td><%= funcionario.secretaria %></td>
            <td><%= funcionario.unidade %></td>
            <td>
            
    <% if current_user.admin? %>
              <%= link_to "Mostrar", funcionario, class: "btn btn-primary" %>
              <%= button_to "Deletar", funcionario, method: :delete, class: "btn btn-danger"%>
              <%= link_to "Editar", edit_funcionario_path(funcionario), class: "btn btn-warning"%>
       <% end %>
              
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<!-- Barra de Navegação -->

app/views/funcionarios/new.html.erb
<h1>Novo funcionario</h1>

<%= render "form", funcionario: @funcionario %>

<br>

<div>
  <%= link_to "Voltar para funcionarios", funcionarios_path %>
</div>

app/views/funcionarios/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @funcionario %>

<div>
  <%= link_to "Editar", edit_funcionario_path(@funcionario) %> |
  <%= link_to "Voltar", funcionarios_path %>

  <%= button_to "Deletar", @funcionario, method: :delete %>
</div>

app/views/inicio/index.html.erb
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">


<h1>Bem vindo ao sistema do SEMAD</h1>
 <p> selecione uma opção</p>
    <ul>
           <li><%= link_to "Funcionarios" , funcionarios_path  %></li>
           <li> <%= link_to "Visitantes" , visitantes_path  %></li>
    </ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
  
<html>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
 <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
  <head>

    <title>SistemaControleVisitas</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" role="navigation" style="z-index: 1000;">
  <div class="container">
   <% if user_signed_in? %>
  <a class="navbar-brand" href="#">Bem-vindo <%= current_user.email %> </a>
<% end %>
    <button class="navbar-toggler border-0" type="button" data-toggle="collapse" data-target="#exCollapsingNavbar">
      &#9776;
    </button>
    <div class="collapse navbar-collapse" id="exCollapsingNavbar">
      <ul class="nav navbar-nav">
        <li class="nav-item"><%= link_to "Gerenciar visitantes", visitantes_path, class: "nav-link" %></li>
        <li class="nav-item"><%= link_to "Gerenciar Funcionarios", funcionarios_path, class: "nav-link" %></li>
      </ul>
      <ul class="nav navbar-nav ml-auto">
        <li class="nav-item">
          <%= form_tag destroy_user_session_path, method: :delete, class: "nav-link" do %>
          <% if user_signed_in? %>
            <%= submit_tag "Sair", class: "btn btn-danger" %>
            <%end%>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>




  </head>
  <body>
  <div class="container mt-5" style="padding-top: 15px;">
    <%= yield %>
  </body>
</html>

app/views/visitantes/_form.html.erb
<%= form_with(model: visitante) do |form| %>
  <% if visitante.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(visitante.errors.count, "error") %> prohibited this visitante from being saved:</h2>

      <ul>
        <% visitante.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= form.label :nome, style: "display: block" %>
    <%= form.text_field :nome %>
  </div>

  <div>
    <%= form.label :cpf, style: "display: block" %>
    <%= form.text_field :cpf %>
  </div>

  <div>
    <%= form.label :rg, style: "display: block" %>
    <%= form.text_field :rg %>
  </div>

  <div>
    <%= form.label :telefone, style: "display: block" %>
    <%= form.text_field :telefone %>
  </div>

  <div>
    <%= form.label :foto, style: "display: block" %>
    <%= form.file_field :foto %>
  </div>

  <div>
    <%= form.label :visitou_em, style: "display: block" %>
    <%= form.datetime_field :visitou_em %>
  </div>

  <div>
    <%= form.submit %>
  </div>

<% end %>

app/views/visitantes/_visitante.html.erb
<div id="<%= dom_id visitante %>">
  <p>
    <strong>Nome:</strong>
    <%= visitante.nome %>
  </p>

  <p>
    <strong>CPF:</strong>
    <%= visitante.cpf %>
  </p>

  <p>
    <strong>RG:</strong>
    <%= visitante.rg %>
  </p>

  <p>
    <strong>Telefone:</strong>
    <%= visitante.telefone %>
  </p>

  <p>
    <strong>Foto:</strong>
    <%= visitante.foto %>
  </p>

  <p>
    <strong>Visitou em:</strong>
    <%= visitante.visitou_em %>
  </p>

</div>

app/views/visitantes/edit.html.erb
<h1>Editing visitante</h1>

<%= render "form", visitante: @visitante %>

<br>

<div>
  <%= link_to "Show this visitante", @visitante %> |
  <%= link_to "Back to visitantes", visitantes_path %>
</div>

app/views/visitantes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Visitantes</h1>

<div id="visitantes">
  <table class="table table-striped table-bordered">
      <%= link_to "Adicionar visitante", new_visitante_path, class: "btn btn-success" %>
      <p></p>
    <thead>
      <tr>
        <th>Nome</th>
        <th>CPF</th>
        <th>Telefone</th>
        <th>RG</th>
        <th>Visitou em:</th>
      </tr>
    </thead>
    <tbody>
      <% @visitantes.each do |visitante| %>
        <tr>
          <td><%= visitante.nome %></td>
          <td><%= visitante.cpf %></td>
          <td><%= visitante.telefone %></td>
          <td><%= visitante.rg %></td>
          <td><%= visitante.visitou_em %></td>
          <td>
          <%= link_to "Mostrar", visitante, class: "btn btn-primary" %></td>
         <td> <%= button_to "Deletar", visitante, method: :delete, class: "btn btn-danger"%> </td>
          <td><%= link_to "Editar", edit_visitante_path(visitante), class: "btn btn-warning"%>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<%= link_to "Adicionar visitante", new_visitante_path %>

app/views/visitantes/new.html.erb
<h1>New visitante</h1>

<%= render "form", visitante: @visitante %>

<br>

<div>
  <%= link_to "Back to visitantes", visitantes_path %>
</div>

app/views/visitantes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @visitante %>
<!-- app/views/visitantes/show.html.erb -->
<h1><%= @visitante.nome %></h1>

<% if @visitante.foto.present? && @visitante.foto.file.present? %>
  <%= image_tag @visitante.foto.url %>
<% else %>
  <p>Nenhuma foto disponível.</p>
<% end %>

<div>
  <%= link_to "Editar visitante", edit_visitante_path(@visitante) %> |
  <%= link_to "Voltar", visitantes_path %>

  <%= button_to "Apagar visitante", @visitante, method: :delete %>
</div>